# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.backgroundErrors", 1);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1377615216);
user_pref("app.update.lastUpdateTime.background-update-timer", 1377615096);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1377615336);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1377625967);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1377614976);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.dir", "/Users/akshay/Downloads");
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.slowStartup.averageTime", 4763);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage", "about:home");
user_pref("browser.startup.homepage_override.buildID", "20130814063812");
user_pref("browser.startup.homepage_override.mstone", "23.0.1");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1377701255616");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1377614855615");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.firstPaint", 726);
user_pref("datareporting.sessions.current.main", 75);
user_pref("datareporting.sessions.current.sessionRestored", 746);
user_pref("datareporting.sessions.current.startTime", "1377668544207");
user_pref("datareporting.sessions.current.totalTime", 11);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1377614851529,\"a\":26,\"t\":10915,\"c\":true,\"m\":70,\"fp\":402,\"sr\":7160}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1377625843886,\"a\":1,\"t\":350,\"c\":true,\"m\":1601,\"fp\":6111,\"sr\":6295}");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:23.0.1");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/Applications/Firefox.app/Contents/MacOS/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1376494068000,\"rdfTime\":1376492443000}}}]");
user_pref("extensions.lastAppVersion", "23.0.1");
user_pref("extensions.lastPlatformVersion", "23.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("font.language.group", "x-western");
user_pref("gecko.buildID", "20130814063812");
user_pref("gecko.mstone", "23.0.1");
user_pref("gfx.blacklist.webgl.msaa", 4);
user_pref("idle.lastDailyNotification", 1377617858);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.ssl", "127.0.0.1");
user_pref("network.proxy.ssl_port", 8000);
user_pref("network.proxy.type", 1);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1377617859);
user_pref("places.history.expiration.transient_current_max_pages", 104019);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1377617859);
user_pref("toolkit.startup.last_success", 1377668544);
user_pref("toolkit.telemetry.previousBuildID", "20130814063812");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1380206862);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
